-- Georgia Safe — reference data seed (Phase 4.2)
-- Auto-generated from src/data/*.json. Idempotent: re-running upserts by id.

insert into public.zones (id, name_en, name_ka, name_ru, day_score, night_score, day_level, night_level, lat, lng, tips_en, tips_ka, tips_ru) values
  ('old_tbilisi', 'Old Tbilisi', 'ძველი თბილისი', 'Старый Тбилиси', 90, 65, 'green', 'yellow', 41.6934, 44.8015, ARRAY['Stick to the well-lit main streets like Shardeni and Erekle II at night.', 'Watch for pickpockets in crowded tourist spots near the churches and squares.', 'Many cafes stay open late and are a safe place to duck into if you feel uneasy.']::text[], ARRAY['ღამით მიჰყევი კარგად განათებულ მთავარ ქუჩებს, როგორიცაა შარდენი და ერეკლე II.', 'ფრთხილად იყავი ჯიბგირების მიმართ ხალხმრავალ ტურისტულ ადგილებში ეკლესიებთან და მოედნებთან.', 'ბევრი კაფე გვიან საათებამდეა ღია და უსაფრთხო თავშესაფარია, თუ არაკომფორტულად იგრძნობ თავს.']::text[], ARRAY['Ночью держитесь хорошо освещённых главных улиц, таких как Шардени и Эрекле II.', 'Будьте внимательны к карманникам в людных туристических местах у церквей и площадей.', 'Многие кафе работают допоздна и являются безопасным местом, куда можно зайти, если почувствуете себя неуютно.']::text[]),
  ('rustaveli', 'Rustaveli Avenue', 'რუსთაველის გამზირი', 'Проспект Руставели', 94, 78, 'green', 'green', 41.6977, 44.7975, ARRAY['The main avenue is well-lit, patrolled, and has security cameras throughout.', 'Busy with pedestrians until late — one of the safest areas at night.', 'Official taxis and metro (Rustaveli station) are easy to find here.']::text[], ARRAY['მთავარი გამზირი კარგადაა განათებული, პატრულირებადი და კამერებით სავსე.', 'გვიან საათებამდე ხალხმრავალია — ღამით ერთ-ერთი ყველაზე უსაფრთხო ადგილია.', 'ოფიციალური ტაქსები და მეტრო (რუსთაველის სადგური) აქ ადვილად საპოვნია.']::text[], ARRAY['Главный проспект хорошо освещён, патрулируется и оснащён камерами наблюдения.', 'Оживлённо пешеходами допоздна — один из самых безопасных районов ночью.', 'Официальные такси и метро (станция Руставели) легко найти здесь.']::text[]),
  ('vera', 'Vera', 'ვერა', 'Вера', 85, 70, 'green', 'yellow', 41.7133, 44.7864, ARRAY['Quiet, mostly residential — safe but fewer people around late at night.', 'Vera Park is pleasant by day, less lit in the evening.']::text[], ARRAY['მშვიდი, ძირითადად საცხოვრებელი უბანია — უსაფრთხოა, მაგრამ გვიან ღამით ნაკლები ხალხია.', 'ვერას პარკი დღისით სასიამოვნოა, საღამოს ნაკლებადაა განათებული.']::text[], ARRAY['Тихий, преимущественно жилой район — безопасно, но поздно ночью меньше людей.', 'Парк Вера приятен днём, вечером освещён хуже.']::text[]),
  ('vake', 'Vake', 'ვაკე', 'Ваке', 92, 80, 'green', 'green', 41.7151, 44.7563, ARRAY['Upscale residential area, popular with families, well-lit main streets.', 'Vake Park is safe for evening walks but stick to the lit paths.', 'Good area for international-standard clinics and pharmacies.']::text[], ARRAY['ელიტური საცხოვრებელი უბანია, პოპულარულია ოჯახებში, მთავარი ქუჩები კარგადაა განათებული.', 'ვაკის პარკი უსაფრთხოა საღამოს სეირნობისთვის, მაგრამ განათებულ ბილიკებს მიჰყევი.', 'კარგი უბანია საერთაშორისო სტანდარტის კლინიკებისა და აფთიაქებისთვის.']::text[], ARRAY['Престижный жилой район, популярен среди семей, главные улицы хорошо освещены.', 'Парк Ваке безопасен для вечерних прогулок, но держитесь освещённых дорожек.', 'Хороший район с клиниками и аптеками международного стандарта.']::text[]),
  ('saburtalo', 'Saburtalo', 'საბურთალო', 'Сабуртало', 83, 68, 'green', 'yellow', 41.7256, 44.7519, ARRAY['Large student and residential district — generally safe, busy during the day.', 'Stick to main roads like Vazha-Pshavela Avenue at night.']::text[], ARRAY['დიდი სტუდენტური და საცხოვრებელი რაიონია — ზოგადად უსაფრთხო, დღისით ხალხმრავალი.', 'ღამით მიჰყევი მთავარ გზებს, როგორიცაა ვაჟა-ფშაველას გამზირი.']::text[], ARRAY['Крупный студенческий и жилой район — в целом безопасно, оживлённо днём.', 'Ночью держитесь главных дорог, таких как проспект Важа-Пшавела.']::text[]),
  ('marjanishvili', 'Marjanishvili', 'მარჯანიშვილი', 'Марджанишвили', 80, 60, 'green', 'yellow', 41.7107, 44.8079, ARRAY['Busy market and nightlife area — keep bags zipped and close in crowds.', 'Popular bars at night draw crowds, which helps safety but watch your drink and belongings.']::text[], ARRAY['საქმიანი ბაზრობისა და ღამის ცხოვრების უბანია — ჩანთა დაკეტილი გქონდეს ხალხმრავლობაში.', 'ღამით ბარები ხალხს იზიდავს, რაც უსაფრთხოებას ეხმარება, მაგრამ ყურადღება მიაქციე სასმელსა და ნივთებს.']::text[], ARRAY['Оживлённый рыночный и ночной район — держите сумки закрытыми в толпе.', 'Ночью бары привлекают толпы, что повышает безопасность, но следите за напитком и вещами.']::text[]),
  ('aghmashenebeli', 'Aghmashenebeli Avenue', 'აღმაშენებლის გამზირი', 'Проспект Агмашенебели', 82, 58, 'green', 'yellow', 41.7057, 44.8058, ARRAY['Trendy bar and restaurant strip — fun but watch for pickpocketing among drinking crowds.', 'Well-lit near the main avenue, darker on side streets.']::text[], ARRAY['მოდური ბარებისა და რესტორნების ქუჩაა — სახალისოა, მაგრამ ფრთხილად იყავი ჯიბგირობასთან დაკავშირებით მსმელ ხალხში.', 'მთავარ გამზირთან კარგადაა განათებული, გვერდითი ქუჩები ბნელია.']::text[], ARRAY['Модная улица баров и ресторанов — весело, но остерегайтесь карманников среди пьющей толпы.', 'У главного проспекта хорошее освещение, боковые улицы темнее.']::text[]),
  ('chughureti', 'Chughureti', 'ჩუღურეთი', 'Чугурети', 75, 55, 'green', 'yellow', 41.7108, 44.8046, ARRAY['Mixed residential and commercial area near the train station — stay alert around transit hubs.', 'Fine during the day, prefer main roads at night.']::text[], ARRAY['შერეული საცხოვრებელი და კომერციული უბანია რკინიგზის სადგურთან — იყავი ფხიზლად სატრანზიტო კვანძებთან.', 'დღისით ნორმალურია, ღამით მთავარ გზებს მიჰყევი.']::text[], ARRAY['Смешанный жилой и коммерческий район у железнодорожного вокзала — будьте внимательны у транзитных узлов.', 'Днём спокойно, ночью держитесь главных дорог.']::text[]),
  ('avlabari', 'Avlabari', 'ავლაბარი', 'Авлабари', 78, 62, 'green', 'yellow', 41.6926, 44.8103, ARRAY['Near government buildings and Holy Trinity Cathedral — moderate foot traffic and lighting.', 'Generally calm, but quieter side streets are less lit at night.']::text[], ARRAY['მთავრობის შენობებთან და სამების ტაძართან ახლოსაა — ზომიერი ფეხით მოსიარულეთა ნაკადი და განათება.', 'ზოგადად მშვიდია, მაგრამ უფრო ჩუმი გვერდითი ქუჩები ღამით ნაკლებადაა განათებული.']::text[], ARRAY['Рядом с правительственными зданиями и Собором Святой Троицы — умеренный пешеходный поток и освещение.', 'В целом спокойно, но более тихие боковые улицы ночью хуже освещены.']::text[]),
  ('ortachala', 'Ortachala', 'ორთაჭალა', 'Ортачала', 60, 38, 'yellow', 'red', 41.6789, 44.8158, ARRAY['Industrial and transit area (near the international bus station) — fewer people around at night.', 'Better to use a taxi rather than walk here after dark.']::text[], ARRAY['სამრეწველო და სატრანზიტო უბანია (საერთაშორისო ავტობუსის სადგურთან ახლოს) — ღამით ნაკლები ხალხია.', 'სჯობია ტაქსით გადაადგილება, ვიდრე ბნელში ფეხით სიარული.']::text[], ARRAY['Промышленный и транзитный район (рядом с международной автостанцией) — ночью меньше людей.', 'Лучше воспользоваться такси, чем идти пешком после наступления темноты.']::text[]),
  ('didube', 'Didube', 'დიდუბე', 'Дидубе', 58, 35, 'yellow', 'red', 41.7387, 44.7838, ARRAY['Major bus/marshrutka station area — higher pickpocket and overcharging risk, stay alert.', 'Avoid walking here alone at night; use official taxis instead.']::text[], ARRAY['დიდი ავტობუსების/მარშრუტკების სადგურის ტერიტორიაა — ჯიბგირობისა და გადაფასების მაღალი რისკია, იყავი ფხიზლად.', 'ღამით მარტო ნუ იარები; სანაცვლოდ ოფიციალურ ტაქსებს გამოიყენე.']::text[], ARRAY['Крупный автобусный/маршрутный вокзал — повышенный риск карманных краж и завышения цен, будьте бдительны.', 'Не ходите здесь одни ночью; вместо этого пользуйтесь официальными такси.']::text[]),
  ('gldani', 'Gldani', 'გლდანი', 'Глдани', 65, 42, 'yellow', 'red', 41.7822, 44.7649, ARRAY['Large residential district far from the center — safe by day, poorly lit in many areas at night.', 'Not a typical tourist area; mainly relevant if staying with locals.']::text[], ARRAY['დიდი საცხოვრებელი რაიონია ცენტრიდან შორს — დღისით უსაფრთხო, ღამით ბევრ ადგილას ცუდადაა განათებული.', 'არ არის ტიპური ტურისტული ადგილი; მნიშვნელოვანია მხოლოდ თუ ადგილობრივებთან ჩერდები.']::text[], ARRAY['Крупный жилой район вдали от центра — безопасен днём, во многих местах плохо освещён ночью.', 'Не типичное туристическое место; актуально, только если вы остановились у местных жителей.']::text[]),
  ('varketili', 'Varketili', 'ვარკეთილი', 'Варкетили', 62, 40, 'yellow', 'red', 41.7213, 44.871, ARRAY['Residential outskirts with less foot traffic at night.', 'Rare for tourists to stay here; if you do, prefer taxis after dark.']::text[], ARRAY['საცხოვრებელი გარეუბანია ნაკლები ფეხით მოსიარულით ღამით.', 'იშვიათია ტურისტისთვის აქ დარჩენა; თუ ხდება, ღამით ტაქსს ამჯობინე.']::text[], ARRAY['Жилая окраина с меньшим пешеходным движением ночью.', 'Туристы редко здесь останавливаются; если это ваш случай, ночью предпочитайте такси.']::text[]),
  ('isani', 'Isani', 'ისანი', 'Исани', 68, 45, 'yellow', 'red', 41.6959, 44.8321, ARRAY['Mixed residential and market area — fine by day, quieter and less lit at night.', 'Metro access is convenient during the day.']::text[], ARRAY['შერეული საცხოვრებელი და სავაჭრო უბანია — დღისით ნორმალურია, ღამით უფრო ჩუმი და ნაკლებადაა განათებული.', 'მეტროზე წვდომა დღისით მოსახერხებელია.']::text[], ARRAY['Смешанный жилой и торговый район — днём нормально, ночью тише и хуже освещён.', 'Доступ к метро удобен днём.']::text[]),
  ('samgori', 'Samgori', 'სამგორი', 'Самгори', 55, 33, 'yellow', 'red', 41.7069, 44.8501, ARRAY['Known market and industrial area with a higher rate of petty theft reports.', 'Best avoided on foot after dark — use official taxis.']::text[], ARRAY['ცნობილი სავაჭრო და სამრეწველო უბანია წვრილმანი ქურდობის მაღალი მაჩვენებლით.', 'სჯობია თავი აარიდო ღამით ფეხით სიარულს — გამოიყენე ოფიციალური ტაქსი.']::text[], ARRAY['Известный торгово-промышленный район с повышенным уровнем мелких краж.', 'Лучше избегать пеших прогулок ночью — пользуйтесь официальным такси.']::text[])
on conflict (id) do update set name_en=excluded.name_en, name_ka=excluded.name_ka, name_ru=excluded.name_ru, day_score=excluded.day_score, night_score=excluded.night_score, day_level=excluded.day_level, night_level=excluded.night_level, lat=excluded.lat, lng=excluded.lng, tips_en=excluded.tips_en, tips_ka=excluded.tips_ka, tips_ru=excluded.tips_ru;

insert into public.scams (id, title_en, title_ka, title_ru, description_en, description_ka, description_ru, location_hint, location_hint_ka, location_hint_ru, severity, category) values
  ('taxi_airport_overcharge', 'Airport taxi overcharging', 'აეროპორტის ტაქსის გადაფასება', 'Завышение цен таксистами в аэропорту', 'Unmarked drivers at Tbilisi Airport arrivals hall quote inflated flat fares, often 3-5x the normal price, before you even get in the car.', 'თბილისის აეროპორტის ჩამოსვლის დარბაზში არამარკირებული მძღოლები გთავაზობენ გაბერილ ფიქსირებულ ფასებს, ხშირად ნორმალურის 3-5-ჯერ მეტს, სანამ მანქანაში საერთოდ ჩასხდებოდე.', 'Немаркированные водители в зале прилёта аэропорта Тбилиси называют завышенные фиксированные цены, часто в 3-5 раз выше обычной, ещё до посадки в машину.', 'Tbilisi International Airport, arrivals hall', 'თბილისის საერთაშორისო აეროპორტი, ჩამოსვლის დარბაზი', 'Международный аэропорт Тбилиси, зал прилёта', 'high', 'taxi'),
  ('bar_friendly_stranger', '"Friendly stranger" bar bill scam', '"მეგობრული უცნობის" ბარის ანგარიშის თაღლითობა', 'Афера с барным счётом от "дружелюбного незнакомца"', 'A friendly local invites you for a drink at a specific bar or restaurant. The bill arrives with a huge inflated total, and staff can be intimidating about payment.', 'მეგობრული ადგილობრივი გპატიჟებს დასალევად კონკრეტულ ბარში ან რესტორანში. ანგარიში მოდის უზარმაზარი გაბერილი ჯამით, ხოლო პერსონალი შეიძლება მუქარით მოითხოვდეს გადახდას.', 'Дружелюбный местный житель приглашает вас выпить в конкретном баре или ресторане. Счёт приходит с огромной завышенной суммой, а персонал может агрессивно требовать оплаты.', 'Old Tbilisi and nightlife strips near Rustaveli / Aghmashenebeli', 'ძველი თბილისი და ღამის ცხოვრების ქუჩები რუსთაველთან/აღმაშენებელთან ახლოს', 'Старый Тбилиси и ночные улицы рядом с Руставели/Агмашенебели', 'high', 'bar'),
  ('currency_exchange_rate_trick', 'Currency exchange rate tricks', 'სავალუტო გაცვლის კურსის ხრიკები', 'Уловки с курсом обмена валюты', 'Some small exchange booths display an attractive rate for large amounts only, or recalculate at a worse rate once you''ve handed over your cash.', 'ზოგიერთი პატარა გამცვლელი პუნქტი აჩვენებს მიმზიდველ კურსს მხოლოდ დიდი თანხებისთვის, ან ცვლის კურსს უარესზე მას შემდეგ, რაც ნაღდ ფულს უკვე გადასცემ.', 'Некоторые небольшие обменные пункты показывают привлекательный курс только для крупных сумм или пересчитывают по худшему курсу уже после того, как вы передали наличные.', 'Small independent exchange booths, especially near tourist areas', 'პატარა დამოუკიდებელი გამცვლელი პუნქტები, განსაკუთრებით ტურისტულ ზონებთან ახლოს', 'Небольшие независимые обменные пункты, особенно рядом с туристическими зонами', 'medium', 'exchange'),
  ('free_bracelet_souvenir', '"Free" souvenir or bracelet', '"უფასო" სუვენირი ან სამაჯური', '"Бесплатный" сувенир или браслет', 'Someone ties a bracelet on your wrist or hands you a "gift" then aggressively demands payment for it.', 'ვიღაც გიბამს სამაჯურს მაჯაზე ან გაწვდის "საჩუქარს", შემდეგ კი აგრესიულად მოითხოვს მის ღირებულებას.', 'Кто-то завязывает вам браслет на запястье или вручает "подарок", а затем агрессивно требует за него оплату.', 'Old Town squares and pedestrian streets', 'ძველი ქალაქის მოედნები და ქვეითთა ქუჩები', 'Площади и пешеходные улицы Старого города', 'low', 'street'),
  ('market_pickpocketing', 'Distraction theft in crowded markets', 'ყურადღების გადატანით ქურდობა ხალხმრავალ ბაზრებში', 'Карманные кражи с отвлечением внимания на рынках', 'Pickpocketing using distraction techniques (bumping, asking for directions, group crowding) in busy market areas.', 'ჯიბგირობა ყურადღების გადატანის ხერხებით (შეჯახება, გზის კითხვა, ჯგუფური შემოხვევა) დაკავებულ სავაჭრო ზონებში.', 'Карманные кражи с использованием отвлекающих приёмов (толчки, вопросы о направлении, окружение группой) в оживлённых рыночных зонах.', 'Dry Bridge Market, Dezerter Bazaar', 'მშრალი ხიდის ბაზარი, დეზერტირის ბაზარი', 'Рынок Сухой мост, Дезертирский рынок', 'medium', 'street'),
  ('fake_police', 'Fake police asking for documents or money', 'ყალბი პოლიციელები, რომლებიც საბუთებს ან ფულს ითხოვენ', 'Фальшивая полиция требует документы или деньги', 'Individuals posing as plain-clothes police ask to see your passport or wallet, then attempt to extract cash. Real police carry visible ID and wear uniforms in almost all situations.', 'პირები, რომლებიც თავს პლაინკლოუზ პოლიციელებად აცხადებენ, პასპორტის ან საფულის ნახვას ითხოვენ, შემდეგ კი ცდილობენ ნაღდი ფულის გამორთმევას. ნამდვილი პოლიცია თითქმის ყველა შემთხვევაში ატარებს ხილულ ID-ს და უნიფორმას.', 'Люди, выдающие себя за полицейских в штатском, просят показать паспорт или кошелёк, а затем пытаются вымогать наличные. Настоящая полиция почти всегда носит видимое удостоверение и форму.', 'Tourist-heavy areas citywide', 'ტურისტებით სავსე ზონები მთელ ქალაქში', 'Туристические зоны по всему городу', 'high', 'street'),
  ('pushy_tour_touts', 'Pushy unofficial tour guides', 'ნაძალადევი არაოფიციალური გიდები', 'Навязчивые неофициальные гиды', 'Unofficial guides near major churches and landmarks pressure tourists into paid tours at inflated prices.', 'არაოფიციალური გიდები მთავარი ეკლესიებისა და ღირსშესანიშნაობების მახლობლად ტურისტებზე ზეწოლას ახდენენ ფასიან ტურებზე გაბერილ ფასებში.', 'Неофициальные гиды рядом с главными церквями и достопримечательностями давят на туристов, навязывая платные туры по завышенным ценам.', 'Near Old Town churches and Narikala Fortress', 'ძველი ქალაქის ეკლესიებთან და ნარიყალას ციხესთან ახლოს', 'Рядом с церквями Старого города и крепостью Нарикала', 'low', 'street'),
  ('no_price_menu', 'Menu without prices / inflated tourist bill', 'მენიუ ფასების გარეშე / გაბერილი ტურისტული ანგარიში', 'Меню без цен / завышенный туристический счёт', 'Some restaurants near tourist attractions hand tourists a different menu without prices, then charge significantly more than locals pay.', 'ზოგიერთი რესტორანი ტურისტული ღირსშესანიშნაობების მახლობლად ტურისტებს აძლევს განსხვავებულ მენიუს ფასების გარეშე, შემდეგ კი მნიშვნელოვნად მეტს ითხოვს, ვიდრე ადგილობრივები იხდიან.', 'Некоторые рестораны рядом с туристическими достопримечательностями дают туристам другое меню без цен, а затем берут значительно больше, чем платят местные.', 'Restaurants directly on major tourist routes', 'რესტორნები პირდაპირ მთავარ ტურისტულ მარშრუტებზე', 'Рестораны прямо на главных туристических маршрутах', 'medium', 'shop'),
  ('taxi_meter_tamper', '"Broken meter" flat-rate taxi', '"გატეხილი მრიცხველი" ფიქსირებული ტარიფის ტაქსი', 'Такси с "неисправным счётчиком" по фиксированному тарифу', 'Drivers claim the meter is broken and negotiate a flat rate that''s well above the normal metered fare.', 'მძღოლები აცხადებენ, რომ მრიცხველი გატეხილია და გვთავაზობენ ფიქსირებულ ტარიფს, რომელიც მნიშვნელოვნად აღემატება ჩვეულებრივ მრიცხველზე ტარიფს.', 'Водители заявляют, что счётчик неисправен, и предлагают фиксированный тариф, значительно превышающий обычную стоимость по счётчику.', 'Streets citywide, especially near hotels and attractions', 'ქუჩები მთელ ქალაქში, განსაკუთრებით სასტუმროებთან და ღირსშესანიშნაობებთან ახლოს', 'Улицы по всему городу, особенно рядом с отелями и достопримечательностями', 'medium', 'taxi'),
  ('wine_tasting_upsell', 'Overpriced "wine tasting" upsell', 'ძვირად გაყიდვის "ღვინის დეგუსტაცია"', 'Завышенная продажа на "дегустации вина"', 'Free or cheap wine tasting offers lead to high-pressure sales of very overpriced bottles, sometimes with claims of rare vintages that don''t hold up.', 'უფასო ან იაფი ღვინის დეგუსტაციის შეთავაზებები მოჰყვება მაღალი წნევის გაყიდვას ძალიან ძვირად ღირებულ ბოთლებზე, ზოგჯერ იშვიათი წლოვანების პრეტენზიით, რაც არ მართლდება.', 'Бесплатные или дешёвые предложения дегустации вина ведут к навязчивой продаже сильно переоценённых бутылок, иногда с ложными заявлениями о редких урожаях.', 'Tourist-oriented wine shops and cellar tours', 'ტურისტზე ორიენტირებული ღვინის მაღაზიები და მარნების ტურები', 'Ориентированные на туристов винные магазины и туры по винным погребам', 'medium', 'shop'),
  ('atm_skimming', 'ATM card skimming', 'ბანკომატის ბარათის სქიმინგი', 'Скимминг банковских карт в банкоматах', 'Standalone ATMs in less monitored locations have occasionally been fitted with card skimming devices. Prefer ATMs attached to bank branches.', 'ცალკე მდგომ ბანკომატებზე ნაკლებად კონტროლირებად ადგილებში ხანდახან დამონტაჟებული იყო ბარათის სქიმინგის მოწყობილობები. ამჯობინე ბანკის ფილიალთან მიმაგრებული ბანკომატები.', 'Отдельно стоящие банкоматы в менее контролируемых местах иногда оснащались устройствами для считывания данных карт. Предпочитайте банкоматы, расположенные при отделениях банков.', 'Standalone street ATMs, especially in less busy areas', 'ცალკე მდგომი ქუჩის ბანკომატები, განსაკუთრებით ნაკლებად დაკავებულ ადგილებში', 'Отдельно стоящие уличные банкоматы, особенно в менее людных местах', 'medium', 'exchange'),
  ('invite_to_family_restaurant', '"Come meet my family" restaurant scam', '"მოდი გაიცანი ჩემი ოჯახი" რესტორნის თაღლითობა', 'Афера с рестораном "познакомься с моей семьёй"', 'An overly friendly stranger invites you to a "family-run" restaurant that turns out to be a staged venue with inflated prices, similar to the friendly-stranger bar scam.', 'ზედმეტად მეგობრული უცნობი გპატიჟებს "საოჯახო" რესტორანში, რომელიც აღმოჩნდება ინსცენირებული ადგილი გაბერილი ფასებით, მსგავსია მეგობრული უცნობის ბარის თაღლითობის.', 'Чрезмерно дружелюбный незнакомец приглашает вас в "семейный" ресторан, который оказывается постановочным местом с завышенными ценами, похоже на аферу с дружелюбным незнакомцем в баре.', 'Old Town and near major hotels', 'ძველი ქალაქი და მთავარ სასტუმროებთან ახლოს', 'Старый город и рядом с крупными отелями', 'high', 'bar'),
  ('cable_car_ticket_resale', 'Inflated cable car / funicular tickets from resellers', 'გაბერილი საბაგირო/ფუნიკულიორის ბილეთები გადამყიდველებისგან', 'Завышенные цены на билеты канатной дороги/фуникулёра у перекупщиков', 'Unofficial sellers near the Narikala cable car or Mtatsminda funicular charge more than the official ticket booth price.', 'არაოფიციალური გამყიდველები ნარიყალას საბაგიროსთან ან მთაწმინდის ფუნიკულიორთან ახლოს ითხოვენ მეტს, ვიდრე ოფიციალური სალაროს ფასია.', 'Неофициальные продавцы рядом с канатной дорогой Нарикала или фуникулёром Мтацминда берут больше, чем стоит билет в официальной кассе.', 'Rike Park cable car station, Mtatsminda funicular station', 'რიყის პარკის საბაგირო სადგური, მთაწმინდის ფუნიკულიორის სადგური', 'Станция канатной дороги в парке Рике, станция фуникулёра Мтацминда', 'low', 'street')
on conflict (id) do update set title_en=excluded.title_en, title_ka=excluded.title_ka, title_ru=excluded.title_ru, description_en=excluded.description_en, description_ka=excluded.description_ka, description_ru=excluded.description_ru, location_hint=excluded.location_hint, location_hint_ka=excluded.location_hint_ka, location_hint_ru=excluded.location_hint_ru, severity=excluded.severity, category=excluded.category;

insert into public.safe_places (id, name, type, address, lat, lng, open_24h) values
  ('pharmacy_aversi_rustaveli', 'Aversi Pharmacy - Rustaveli', 'pharmacy24', 'Rustaveli Ave area, Tbilisi', 41.6981, 44.7978, true),
  ('pharmacy_psp_vake', 'PSP Pharmacy - Vake', 'pharmacy24', 'Vake, Tbilisi', 41.7148, 44.7571, true),
  ('pharmacy_gpc_marjanishvili', 'GPC Pharmacy - Marjanishvili', 'pharmacy24', 'Marjanishvili, Tbilisi', 41.7104, 44.8072, true),
  ('pharmacy_aversi_saburtalo', 'Aversi Pharmacy - Saburtalo', 'pharmacy24', 'Vazha-Pshavela Ave, Saburtalo, Tbilisi', 41.7261, 44.7524, true),
  ('pharmacy_psp_old_town', 'PSP Pharmacy - Old Town', 'pharmacy24', 'Old Tbilisi, Tbilisi', 41.6928, 44.8021, true),
  ('atm_tbc_freedom_square', 'TBC Bank ATM - Freedom Square', 'atm', 'Freedom Square, Tbilisi', 41.6939, 44.8017, true),
  ('atm_bog_rustaveli', 'Bank of Georgia ATM - Rustaveli', 'atm', 'Rustaveli Ave, Tbilisi', 41.6989, 44.7969, true),
  ('atm_tbc_vake_park', 'TBC Bank ATM - Vake Park', 'atm', 'Vake Park area, Tbilisi', 41.7159, 44.7551, true),
  ('atm_bog_saburtalo', 'Bank of Georgia ATM - Saburtalo', 'atm', 'Vazha-Pshavela Ave, Saburtalo, Tbilisi', 41.7249, 44.7512, true),
  ('hospital_amc_vake', 'American Medical Centers (AMC) Vake', 'hospital', '11 Dimitri Arakishvili St, Vake, Tbilisi 0179', 41.715, 44.756, true),
  ('hospital_republican', 'Republican Hospital (N. Kipshidze University Clinic)', 'hospital', '29 Vazha-Pshavela Ave, Tbilisi', 41.726, 44.75, true),
  ('hospital_eristavi', 'K. Eristavi National Surgery Center', 'hospital', '5 Chachava St, Tbilisi', 41.719, 44.752, true),
  ('police_old_tbilisi', 'Old Tbilisi District Police Main Department', 'police', '27 Tabukashvili St, Tbilisi', 41.694, 44.803, true),
  ('police_mia_hq', 'Ministry of Internal Affairs (HQ)', 'police', '4 Gmiri Kursantebi St, Tbilisi', 41.708, 44.775, true),
  ('police_tbilisi_division', 'Tbilisi Police Division', 'police', '136 Tsereteli Ave, Tbilisi', 41.732, 44.775, true),
  ('toilet_tbilisi_mall', 'Tbilisi Mall - Public Restrooms', 'toilet', 'Agmashenebeli Alley, Saburtalo, Tbilisi', 41.737, 44.745, false),
  ('toilet_east_point', 'East Point Mall - Public Restrooms', 'toilet', 'Kakheti Highway, Tbilisi', 41.727, 44.845, false),
  ('toilet_galleria', 'Galleria Tbilisi - Public Restrooms', 'toilet', 'Near Freedom Square, Tbilisi', 41.694, 44.8, false),
  ('toilet_rustaveli_metro', 'Rustaveli Metro Station - Restroom', 'toilet', 'Rustaveli Ave, Tbilisi', 41.7, 44.797, true),
  ('toilet_vake_park', 'Vake Park - Public Restroom', 'toilet', 'Vake Park, Tbilisi', 41.716, 44.75, false)
on conflict (id) do update set name=excluded.name, type=excluded.type, address=excluded.address, lat=excluded.lat, lng=excluded.lng, open_24h=excluded.open_24h;

insert into public.emergency_meta (id, note_en, note_ka, note_ru, national_number, national_number_description_en, national_number_description_ka, national_number_description_ru, health_hotline_number, health_hotline_description_en, health_hotline_description_ka, health_hotline_description_ru, tourist_info_name_en, tourist_info_address, tourist_info_hours, tourist_info_description_en, tourist_info_description_ka, tourist_info_description_ru) values
  (1, 'Contact details compiled from public sources, July 2026. Verify critical numbers before relying on them in a real emergency — always call 112 first.', 'საკონტაქტო დეტალები შედგენილია საჯარო წყაროებიდან, 2026 წლის ივლისი. გადამოწმე კრიტიკული ნომრები რეალურ საგანგებო სიტუაციაში მათზე დაყრდნობამდე — ყოველთვის ჯერ დარეკე 112-ზე.', 'Контактные данные собраны из открытых источников, июль 2026 года. Проверяйте важные номера перед тем, как полагаться на них в реальной чрезвычайной ситуации — всегда сначала звоните 112.', '112', 'Single emergency number in Georgia for police, fire, and ambulance. Free from any phone, available 24/7, English-speaking operators available.', 'საქართველოში ერთიანი საგანგებო ნომერი პოლიციის, სახანძრო და სასწრაფო დახმარებისთვის. უფასოა ნებისმიერი ტელეფონიდან, ხელმისაწვდომია 24/7, არის ინგლისურენოვანი ოპერატორები.', 'Единый номер экстренных служб в Грузии для полиции, пожарной службы и скорой помощи. Бесплатный с любого телефона, доступен круглосуточно, есть англоговорящие операторы.', '1505', 'Georgia Ministry of Health 24/7 hotline for medical guidance and information.', 'საქართველოს ჯანდაცვის სამინისტროს 24/7 ცხელი ხაზი სამედიცინო რჩევებისა და ინფორმაციისთვის.', 'Круглосуточная горячая линия Министерства здравоохранения Грузии для медицинских консультаций и информации.', 'Tbilisi Tourist Information Center', '3 Rustaveli Ave, Tbilisi', '10:00-18:00 daily', 'Free maps, directions, and non-emergency tourist assistance. Not a police station — for emergencies always call 112.', 'უფასო რუკები, მიმართულებები და არასაგანგებო ტურისტული დახმარება. არ არის პოლიციის განყოფილება — საგანგებო სიტუაციებისთვის ყოველთვის დარეკე 112-ზე.', 'Бесплатные карты, указания и неэкстренная помощь туристам. Это не полицейский участок — в экстренных случаях всегда звоните 112.')
on conflict (id) do update set note_en=excluded.note_en, note_ka=excluded.note_ka, note_ru=excluded.note_ru, national_number=excluded.national_number, national_number_description_en=excluded.national_number_description_en, national_number_description_ka=excluded.national_number_description_ka, national_number_description_ru=excluded.national_number_description_ru, health_hotline_number=excluded.health_hotline_number, health_hotline_description_en=excluded.health_hotline_description_en, health_hotline_description_ka=excluded.health_hotline_description_ka, health_hotline_description_ru=excluded.health_hotline_description_ru, tourist_info_name_en=excluded.tourist_info_name_en, tourist_info_address=excluded.tourist_info_address, tourist_info_hours=excluded.tourist_info_hours, tourist_info_description_en=excluded.tourist_info_description_en, tourist_info_description_ka=excluded.tourist_info_description_ka, tourist_info_description_ru=excluded.tourist_info_description_ru;

insert into public.emergency_police (id, name_en, address, phone, description_en, description_ka, description_ru) values
  ('patrol_police', 'Patrol Police Hotline', NULL, '+995 32 241 42 42', 'General patrol police assistance line for non-emergency police matters.', 'პატრულირების პოლიციის ზოგადი დახმარების ხაზი არასაგანგებო პოლიციის საკითხებისთვის.', 'Общая линия помощи патрульной полиции по неэкстренным полицейским вопросам.'),
  ('mia_hq', 'Ministry of Internal Affairs (HQ)', '4 Gmiri Kursantebi St, Tbilisi', '+995 32 241 26 64', 'Main Ministry of Internal Affairs contact office.', 'შინაგან საქმეთა სამინისტროს მთავარი საკონტაქტო ოფისი.', 'Главный контактный офис Министерства внутренних дел.'),
  ('old_tbilisi_district_police', 'Old Tbilisi District Police Main Department', '27 Tabukashvili St, Tbilisi', NULL, 'Local police department covering the Old Town tourist area.', 'ადგილობრივი პოლიციის დეპარტამენტი, რომელიც მოიცავს ძველი ქალაქის ტურისტულ ზონას.', 'Местный полицейский департамент, обслуживающий туристическую зону Старого города.')
on conflict (id) do update set name_en=excluded.name_en, address=excluded.address, phone=excluded.phone, description_en=excluded.description_en, description_ka=excluded.description_ka, description_ru=excluded.description_ru;

insert into public.emergency_hospitals (id, name_en, address, phone, lat, lng, notes_en, notes_ka, notes_ru) values
  ('amc_vake', 'American Medical Centers (AMC) Vake', '11 Dimitri Arakishvili St, Vake, Tbilisi 0179', '+995 32 250 00 20', 41.715, 44.756, '24/7 emergency care, English-speaking staff, direct billing with many international insurers.', '24/7 გადაუდებელი დახმარება, ინგლისურენოვანი პერსონალი, პირდაპირი ანგარიშსწორება ბევრ საერთაშორისო სადაზღვევო კომპანიასთან.', 'Круглосуточная неотложная помощь, англоговорящий персонал, прямые расчёты со многими международными страховщиками.'),
  ('republican_hospital', 'Academic N. Kipshidze University Clinic - Republican Hospital', '29 Vazha-Pshavela Ave, Tbilisi', '+995 32 224 40 33', 41.726, 44.75, 'Major multi-profile hospital with emergency department.', 'დიდი მრავალპროფილური საავადმყოფო გადაუდებელი დახმარების განყოფილებით.', 'Крупная многопрофильная больница с отделением неотложной помощи.'),
  ('eristavi_center', 'K. Eristavi National Experimental and Clinical Surgery Center', '5 Chachava St, Tbilisi', '+995 32 202 25 25', 41.719, 44.752, 'Emergency and surgical care center.', 'გადაუდებელი და ქირურგიული დახმარების ცენტრი.', 'Центр неотложной и хирургической помощи.')
on conflict (id) do update set name_en=excluded.name_en, address=excluded.address, phone=excluded.phone, lat=excluded.lat, lng=excluded.lng, notes_en=excluded.notes_en, notes_ka=excluded.notes_ka, notes_ru=excluded.notes_ru;

insert into public.emergency_embassies (id, country_en, address, phone) values
  ('usa', 'United States', '29 Georgian-American Friendship Ave, Didi Dighomi, Tbilisi 0131', '+995 32 227 7000'),
  ('uk', 'United Kingdom', 'GMT Plaza, 4 Freedom Square, Tbilisi 0105', '+995 32 274 747'),
  ('germany', 'Germany', 'Sheraton Metechi Palace Hotel, 20 Telavi St, Tbilisi 0103', '+995 32 244 7300'),
  ('france', 'France', '15 Gogebashvili St, Tbilisi', '+995 32 999 976'),
  ('israel', 'Israel', '154 Agmashenebeli Ave, Tbilisi 0102', '+995 32 255 6500'),
  ('turkey', 'Turkey', '35 Chavchavadze Ave, Tbilisi', '+995 32 252 072'),
  ('poland', 'Poland', '19 Zubalashvili St, Tbilisi', '+995 32 292 0398'),
  ('ukraine', 'Ukraine', '75 Oniashvili St, Tbilisi 0160', '+995 32 231 1161'),
  ('azerbaijan', 'Azerbaijan', '4 Vakhtang Gorgasali St, Tbilisi', '+995 32 224 2220'),
  ('armenia', 'Armenia', '4 Tetelashvili St, Tbilisi 0102', '+995 32 295 1723')
on conflict (id) do update set country_en=excluded.country_en, address=excluded.address, phone=excluded.phone;
