-- Georgia Safe — admin access for the in-app admin panel.
--
-- Every table in this project so far is either public-read reference data or
-- write-only (feedback, reviews, submissions have an INSERT policy and no
-- SELECT policy at all). That was deliberate: no tourist can read back what
-- anyone else wrote. The admin panel needs to read and change those rows, so
-- this migration adds a second, narrow role on top — without loosening
-- anything for ordinary users.
--
-- Who is admin: a single hardcoded email, checked SERVER-SIDE against the
-- signed-in user's JWT. The app also hides the panel behind the same email in
-- src/lib/admin.ts, but that is only cosmetic — a client check can be patched
-- out of any app. These policies are the real enforcement: even a hand-crafted
-- request with a valid non-admin token is rejected by Postgres.
--
-- To change the admin, or add a second one, edit is_admin() below and add a
-- new migration — do not edit this file once it has been pushed.

create or replace function public.is_admin()
returns boolean
language sql
stable
as $$
  select coalesce(auth.jwt() ->> 'email', '') = 'mishvelidze.u@gmail.com';
$$;

comment on function public.is_admin() is
  'True when the caller is signed in as the app administrator. Used by the admin RLS policies below.';

-- ---------------------------------------------------------------------------
-- place_submissions — approve / reject tourist-submitted places.
--
-- Previously insert-only, with reads going through the place_submissions_public
-- view (which masks rating/comment until approved and never exposes
-- push_token). The admin reads the BASE table instead, so the panel can show
-- pending submissions with their rating and comment before deciding.
-- ---------------------------------------------------------------------------
create policy "Admin read submissions" on public.place_submissions
  for select to authenticated using (public.is_admin());

create policy "Admin update submissions" on public.place_submissions
  for update to authenticated using (public.is_admin()) with check (public.is_admin());

create policy "Admin delete submissions" on public.place_submissions
  for delete to authenticated using (public.is_admin());

-- ---------------------------------------------------------------------------
-- place_reviews and feedback — read-only for the admin.
--
-- No update/delete policy on purpose: these are anonymous tourist opinions,
-- and the panel only ever displays them. Nothing in the app needs to edit
-- someone's review, and not granting the permission means a bug cannot.
-- ---------------------------------------------------------------------------
create policy "Admin read reviews" on public.place_reviews
  for select to authenticated using (public.is_admin());

create policy "Admin read feedback" on public.feedback
  for select to authenticated using (public.is_admin());

-- ---------------------------------------------------------------------------
-- safe_places — full CRUD for the admin (pharmacies, ATMs, hospitals...).
-- Public SELECT already exists from the reference-tables migration and is
-- untouched; these only add write access.
-- ---------------------------------------------------------------------------
create policy "Admin insert safe places" on public.safe_places
  for insert to authenticated with check (public.is_admin());

create policy "Admin update safe places" on public.safe_places
  for update to authenticated using (public.is_admin()) with check (public.is_admin());

create policy "Admin delete safe places" on public.safe_places
  for delete to authenticated using (public.is_admin());

-- ---------------------------------------------------------------------------
-- zones — update only.
--
-- No insert/delete: zone ids are referenced by feedback.zone_id and are
-- baked into the shipped zones.json fallback, so adding or removing one is a
-- code change (new data file + migration), not a runtime action. Editing the
-- day/night scores and tips, which is what actually changes over time, is
-- allowed.
-- ---------------------------------------------------------------------------
create policy "Admin update zones" on public.zones
  for update to authenticated using (public.is_admin()) with check (public.is_admin());

-- ---------------------------------------------------------------------------
-- Review photos live in a PRIVATE bucket (see the place_reviews migration), so
-- the admin panel needs an explicit read policy to display them. Submitted
-- place photos are already in a public bucket and need nothing.
-- ---------------------------------------------------------------------------
create policy "Admin read review photos" on storage.objects
  for select to authenticated
  using (bucket_id = 'place-review-photos' and public.is_admin());
