-- Adds eight verified Tbilisi hospitals to emergency_hospitals.
-- Coordinates cross-checked against OpenStreetMap / Nominatim; phone numbers
-- confirmed against OSM tags or the hospital's own listing (July 2026).
-- Idempotent: re-running refreshes the rows instead of failing on the primary key.

insert into public.emergency_hospitals (id, name_en, address, phone, lat, lng, notes_en, notes_ka, notes_ru) values
  ('caucasus_medical_centre', 'Caucasus Medical Centre (CMC)', '23 Petre Kavtaradze St, Saburtalo, Tbilisi', '+995 32 260 06 00', 41.7221, 44.7315, 'Multi-profile hospital, 24/7 emergency service, English-speaking staff, works with international insurers.', 'მრავალპროფილური საავადმყოფო, 24/7 გადაუდებელი დახმარება, ინგლისურენოვანი პერსონალი, თანამშრომლობს საერთაშორისო სადაზღვევო კომპანიებთან.', 'Многопрофильная больница, круглосуточная неотложная помощь, англоговорящий персонал, работает с международными страховщиками.'),
  ('new_hospitals', 'New Hospitals', '12 Krtsanisi St, Krtsanisi, Tbilisi', '+995 32 219 01 90', 41.675, 44.8245, 'Multi-profile hospital with an emergency department, south of the Old Town.', 'მრავალპროფილური საავადმყოფო გადაუდებელი დახმარების განყოფილებით, ძველი თბილისის სამხრეთით.', 'Многопрофильная больница с отделением неотложной помощи, к югу от Старого города.'),
  ('american_hospital_tbilisi', 'American Hospital Tbilisi (not the same as AMC Vake)', '17 Ushangi Chkheidze St, Tbilisi 0102', '+995 32 200 90 09', 41.7098, 44.7927, 'Multi-profile hospital with a 24/7 emergency department and English-speaking staff. A separate hospital from American Medical Centers (AMC) in Vake.', 'მრავალპროფილური საავადმყოფო 24/7 გადაუდებელი დახმარების განყოფილებითა და ინგლისურენოვანი პერსონალით. ვაკეში მდებარე American Medical Centers-ისგან (AMC) განსხვავებული დაწესებულებაა.', 'Многопрофильная больница с круглосуточным отделением неотложной помощи и англоговорящим персоналом. Это не то же самое, что American Medical Centers (AMC) в Ваке.'),
  ('bokeria_hospital', 'Iv. Bokeria University Hospital', '8 Zurab Iarajuli St, Samgori, Tbilisi 0137', '+995 32 280 16 00', 41.6678, 44.8888, 'Multi-profile hospital with an emergency department, serving the eastern Samgori district.', 'მრავალპროფილური საავადმყოფო გადაუდებელი დახმარების განყოფილებით, ემსახურება აღმოსავლეთით სამგორის რაიონს.', 'Многопрофильная больница с отделением неотложной помощи, обслуживает восточный район Самгори.'),
  ('tbilisi_central_hospital', 'Tbilisi Central Hospital', '1 Konstantine Chachava St, Tbilisi 0159', '+995 32 210 44 44', 41.7751, 44.7765, 'Multi-profile hospital with a 24/7 emergency department and acute surgery.', 'მრავალპროფილური საავადმყოფო 24/7 გადაუდებელი დახმარების განყოფილებითა და გადაუდებელი ქირურგიით.', 'Многопрофильная больница с круглосуточным отделением неотложной помощи и экстренной хирургией.'),
  ('khechinashvili_clinic', 'S. Khechinashvili University Clinic', '33 Ilia Chavchavadze Ave, Tbilisi 0179', '+995 32 221 44 00', 41.7116, 44.762, 'University hospital with an emergency department and a wide range of surgical care.', 'საუნივერსიტეტო საავადმყოფო გადაუდებელი დახმარების განყოფილებითა და ფართო ქირურგიული მომსახურებით.', 'Университетская больница с отделением неотложной помощи и широким спектром хирургической помощи.'),
  ('tsmu_first_clinic', 'TSMU First University Clinic', '4 Gudamakari St, Gldani-Nadzaladevi, Tbilisi', '+995 32 261 01 01', 41.7693, 44.7966, 'State university hospital with an emergency medicine department, in the north of the city.', 'სახელმწიფო საუნივერსიტეტო საავადმყოფო გადაუდებელი მედიცინის განყოფილებით, ქალაქის ჩრდილოეთით.', 'Государственная университетская больница с отделением экстренной медицины, на севере города.'),
  ('mediclub_georgia', 'MediClubGeorgia', '22a Tashkenti St, Tbilisi 0160', '+995 32 225 19 91', 41.7284, 44.7633, 'International medical centre, English-speaking staff, accepts international insurance. Call ahead — not a full 24/7 emergency hospital.', 'საერთაშორისო სამედიცინო ცენტრი, ინგლისურენოვანი პერსონალი, იღებს საერთაშორისო დაზღვევას. ჯერ დარეკე — სრული 24/7 გადაუდებელი საავადმყოფო არ არის.', 'Международный медицинский центр, англоговорящий персонал, принимает международную страховку. Сначала позвоните — это не полноценная круглосуточная больница скорой помощи.')
on conflict (id) do update set name_en=excluded.name_en, address=excluded.address, phone=excluded.phone, lat=excluded.lat, lng=excluded.lng, notes_en=excluded.notes_en, notes_ka=excluded.notes_ka, notes_ru=excluded.notes_ru;

-- The same hospitals as map pins, so the "Hospitals" layer matches the
-- Emergency screen. MediClubGeorgia is not open_24h: it is an international
-- clinic with daytime hours, not a round-the-clock emergency hospital.
insert into public.safe_places (id, name, type, address, lat, lng, open_24h) values
  ('hospital_caucasus_medical_centre', 'Caucasus Medical Centre (CMC)', 'hospital', '23 Petre Kavtaradze St, Saburtalo, Tbilisi', 41.7221, 44.7315, true),
  ('hospital_new_hospitals', 'New Hospitals', 'hospital', '12 Krtsanisi St, Krtsanisi, Tbilisi', 41.675, 44.8245, true),
  ('hospital_american_tbilisi', 'American Hospital Tbilisi (not AMC Vake)', 'hospital', '17 Ushangi Chkheidze St, Tbilisi 0102', 41.7098, 44.7927, true),
  ('hospital_bokeria', 'Iv. Bokeria University Hospital', 'hospital', '8 Zurab Iarajuli St, Samgori, Tbilisi 0137', 41.6678, 44.8888, true),
  ('hospital_tbilisi_central', 'Tbilisi Central Hospital', 'hospital', '1 Konstantine Chachava St, Tbilisi 0159', 41.7751, 44.7765, true),
  ('hospital_khechinashvili', 'S. Khechinashvili University Clinic', 'hospital', '33 Ilia Chavchavadze Ave, Tbilisi 0179', 41.7116, 44.762, true),
  ('hospital_tsmu_first', 'TSMU First University Clinic', 'hospital', '4 Gudamakari St, Gldani-Nadzaladevi, Tbilisi', 41.7693, 44.7966, true),
  ('hospital_mediclub_georgia', 'MediClubGeorgia', 'hospital', '22a Tashkenti St, Tbilisi 0160', 41.7284, 44.7633, false)
on conflict (id) do update set name=excluded.name, type=excluded.type, address=excluded.address, lat=excluded.lat, lng=excluded.lng, open_24h=excluded.open_24h;
